# Generated by Django 5.0.3 on 2024-03-29 10:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=100)),
                ('code_cours', models.CharField(max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('type_sujet', models.CharField(choices=[('TD', 'Travaux Dirigés'), ('TPE', 'Travaux Pratiques Encadrés'), ('CC', 'Contrôle Continu'), ('EXAM', 'Examen')], max_length=4)),
                ('annee', models.IntegerField()),
                ('niveau', models.CharField(choices=[('Niveau 1', 'Niveau 1'), ('Niveau 2', 'Niveau 2'), ('Niveau 3', 'Niveau 3')], max_length=10)),
                ('filiere', models.CharField(choices=[('INFO', 'Informatique'), ('PHYS', 'Physique'), ('CHIM', 'Chimie'), ('MATH', 'Mathématiques'), ('BIO', 'Biologie'), ('SCIE', 'Science')], max_length=4)),
                ('fichier', models.FileField(upload_to='sujets/')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Entrez un numéro CIN valide.')])),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=75)),
                ('telephone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Entrez un numéro de téléphone valide.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
