# Generated by Django 5.0.3 on 2024-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='cours',
            field=models.CharField(choices=[('INF111', "Introduction à L'agorithmique"), ('INF121', 'Introduction aux bases de données'), ('INF131', 'Programmation Structurée en C'), ('INF141', 'Algèbre 1'), ('INF151', 'Anglais Scientifique'), ('INF161', 'Electrostatique du vide')], default='Cours', max_length=100),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='filiere',
            field=models.CharField(choices=[('INFO', 'Informatique'), ('IGE', 'Informatique et Gestion des entreprises'), ('MATH', 'Mathématiques'), ('PHYS', 'Physique'), ('CHIM', 'Chimie'), ('SB', 'Science Biologie'), ('ST', 'Science de la terre')], max_length=100),
        ),
    ]
