# Generated by Django 5.0.3 on 2024-04-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliweb', '0002_sujet_cours_alter_sujet_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='cours',
            field=models.CharField(choices=[('INF111', "Introduction à L'agorithmique"), ('INF121', 'Introduction aux bases de données'), ('INF131', 'Programmation Structurée en C'), ('INF141', 'Algèbre 1'), ('INF151', 'Anglais Scientifique'), ('INF161', 'Electrostatique du vide'), ('INF112', 'Programmation Fonctionnelle'), ('INF122', 'Introduction aux Réseaux '), ('INF132', "Introduction aux Systèmes d'Exploitations "), ('INF142', 'Analyse 1'), ('INF152', 'Electronique Numérique 1 '), ('INF162', 'Statistiques 1 '), ('INF213', 'Programmation Orientée Objet'), ('INF223', 'Architecture des Ordinateurs'), ('INF233', 'Sructure des données'), ('INF243', 'Analyse 2'), ('INF253', 'Anglais Scientifique'), ('INF263', 'Calcul de Probabilité')], default='Cours', max_length=100),
        ),
    ]
