# Generated by Django 5.0.3 on 2024-04-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliweb', '0004_alter_sujet_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='cours',
            field=models.CharField(choices=[('INF111', "Introduction à L'agorithmique"), ('INF121', 'Introduction aux bases de données'), ('INF131', 'Programmation Structurée en C'), ('INF141', 'Algèbre 1'), ('INF151', 'Anglais Scientifique'), ('INF161', 'Electrostatique du vide'), ('INF112', 'Programmation Fonctionnelle'), ('INF122', 'Introduction aux Réseaux '), ('INF132', "Introduction aux Systèmes d'Exploitations "), ('INF142', 'Analyse 1'), ('INF152', 'Electronique Numérique 1 '), ('INF162', 'Statistiques 1 '), ('INF213', 'Programmation Orientée Objet'), ('INF223', 'Architecture des Ordinateurs'), ('INF233', 'Sructure des données'), ('INF243', 'Analyse 2'), ('INF253', 'Anglais Scientifique'), ('INF263', 'Calcul de Probabilité'), ('INF214', "Systèmes d'Information"), ('INF224', 'Génie Logiciel 1'), ('INF234', 'Programmation Web'), ('INF244', 'Algèbre 2'), ('INF254', 'Electronique 2'), ('INF264', 'Calcul Scientique'), ('INF315', 'Analyse et Conception des Algorithmes'), ('INF325', 'Languages Formels'), ('INF335', 'Anglais Scientifique'), ('INF345', 'Génie Logiciel 2'), ('INF355', 'Théorie des ensembles et logique mathématique'), ('INF365', 'Recherche Opérationnelle'), ('BIO111', 'Biologie Structurale et Fonctionnelle  de la Cellule'), ('BIO121', 'Biologie Moléculaire de la Cellule'), ('BIO131', 'Mathématiques de Sciences Biologiques'), ('BIO141', 'Chimie_Physique'), ('BIO151', 'Anglais Scientifique'), ('BIO161', 'Biodiversité'), ('BIO171', 'Systématique'), ('BIO112', 'Géologie Générale'), ('BIO122', 'Chimie des Solutions'), ('BIO132', 'Biologie Générale'), ('BIO142', 'Physique Générale'), ('BIO152', 'Mathématiques Statistiques'), ('BIO172', 'Apiculture, Aquaculture et Pépinières'), ('BIO213', 'Grands Groupes des Végétaux'), ('BIO223', 'Physiologie Végétale'), ('BIO233', 'Génétique Médelienne'), ('BIO243', 'Biochimie Structurale'), ('BIO253', 'Anglais Scientifique'), ('BIO263', 'Informatiques'), ('BIO214', 'Physiologie Animale'), ('BIO224', 'Microbiologie'), ('BIO234', 'Chimie Organique'), ('BIO244', 'Chimie Analytique'), ('BIO254', 'Ecologie générale'), ('BIO264', 'Biotechnologie'), ('BIO274', 'Introduction à la biologie moléculaire'), ('BIO284', 'Parasitologie'), ('BIO315', ''), ('BIO325', ''), ('BIO335', ''), ('BIO345', ''), ('BIO355', ''), ('BIO365', ''), ('BIO316', ''), ('BIO326', ''), ('BIO336', ''), ('BIO346', ''), ('BIO356', ''), ('BIO366', '')], default='Cours', max_length=100),
        ),
    ]
