# Generated by Django 5.0.4 on 2024-04-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliweb', '0006_alter_sujet_cours_delete_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='filiere',
            field=models.CharField(choices=[('INFO', 'Informatique Fondamentale'), ('IGE', 'Informatique et Gestion des entreprises'), ('MATH', 'Mathématiques'), ('PHYS', 'Physique'), ('CHIM', 'Chimie'), ('SB', 'Science Biologie'), ('ST', 'Science de la terre')], max_length=100),
        ),
    ]
