# Generated by Django 5.0.4 on 2024-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliweb', '0007_alter_sujet_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='filiere',
            field=models.CharField(choices=[('Informatique Fondamentale', 'Informatique Fondamentale'), ('Informatique et Gestion des entreprises', 'Informatique et Gestion des entreprises'), ('Mathématiques', 'Mathématiques'), ('Physique', 'Physique'), ('Chimie', 'Chimie'), ('Science Biologie', 'Science Biologie'), ('Science de la terre', 'Science de la terre')], max_length=100),
        ),
    ]
